### ISSUE TITLE
改了go.js无效？

### ISSUE THREAD

**Issue by ningmengtu** [xmflswood/xmflswood.github.io#1]
已经解决

**Comment by xmflswood** [comment]
@ningmengtu 请问最后是路径的问题吗？

**Comment by ningmengtu** [comment]
不是，里面有一个1.js文件 和 Birthday.js 放在一起的好像发自我的iPhone------------------ 原始邮件 ------------------发件人: xmflswood  <notifications@github.com>发送时间: 2018年2月13日 20:59收件人: xmflswood/xmflswood.github.io <xmflswood.github.io@noreply.github.com>抄送: ningmengtu <m13559104361@163.com>, Mention <mention@noreply.github.com>主题: 回复：[xmflswood/xmflswood.github.io] 改了go.js无效？ (#1)@ningmengtu 请问最后是路径的问题吗？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xmflswood/xmflswood.github.io","title":"xmflswood/xmflswood.github.io","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xmflswood/xmflswood.github.io"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xmflswood in #1: @ningmengtu 请问最后是路径的问题吗？"}],"action":{"name":"View Issue","url":"https://github.com/xmflswood/xmflswood.github.io/issues/1#issuecomment-365259661"}}}
